version: 0.2

phases:
  pre_build:
    commands:
      - REPO_NAME=$(aws ecr describe-repositories --repository-names $ECR_REPOSITORY_NAME_PARAMETER --query 'repositories[0].repositoryName' --output text)
      - REPO_URI=$(aws ecr describe-repositories --repository-names $REPO_NAME --query 'repositories[0].repositoryUri' --output text)
      - echo "ECR Repository Name: $REPO_NAME"
      - echo "ECR Repository URI: $REPO_URI"
      - echo "Logging in to Amazon ECR..."
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo "phase complete!"

  # build:
  #   commands:
  #     - echo "Building the Docker image..."
#       - docker build -t $REPO_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION .
#       - echo "Tagging the Docker image..."
#       - docker tag $REPO_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION $REPO_URI:latest

#   post_build:
#     commands:
#       - echo "Pushing the Docker image to Amazon ECR..."
#       - docker push $REPO_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
#       - docker push $REPO_URI:latest
#       - echo "Writing image definitions file..."
#       - printf '[{"name":"%s","imageUri":"%s"}]' $REPO_NAME $REPO_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION > imagedefinitions.json

# artifacts:
#   files: imagedefinitions.json